### ISSUE TITLE
Calculation order for reduction ambition

### ISSUE THREAD

**Issue by pjankows** [ScienceBasedTargets/SBTi-finance-tool#265]
Could you please make sure the calculation order for this formula is correct:
https://github.com/ScienceBasedTargets/SBTi-finance-tool/blob/323d4c67ac3a46ae28bc9f593635ac681fb5b945/SBTi/target_validation.py#L166

Should't it have added brackets like this:
```
                target.reduction_ambition = (
                    (target.reduction_ambition
                    * target.coverage_s1
                    * target.base_year_ghg_s1
                    + s2.reduction_ambition
                    * s2.coverage_s1
                    * s2.base_year_ghg_s2)
                    / (target.base_year_ghg_s1 + s2.base_year_ghg_s1)
                    / combined_coverage
                )
```
I'm not sure what the correct one should be but the current one can cause reduction_ambition to go above 1.0 and this looks like a bug.

**Comment by cschmidli** [comment]
should be fixed with https://github.com/ScienceBasedTargets/SBTi-finance-tool/releases/tag/v1.0.2. Please re-open if it doesn't work as expected.
