### ISSUE TITLE
Bug in S1S2S3 score aggregation

### ISSUE THREAD

**Issue by dcoulomb** [ScienceBasedTargets/SBTi-finance-tool#274]
When carbon emissions for S1S2 and S3 are missing (np.nan), the tool should return the default score (3.2 by default) for S1S2S3. Instead, it still tries to apply the formula below

[https://github.com/ScienceBasedTargets/SBTi-finance-tool/blob/5cdbcf4f5f7be6bc7bd6a6e1fa77808a96361c88/SBTi/temperature_score.py#L349](https://github.com/ScienceBasedTargets/SBTi-finance-tool/blob/5cdbcf4f5f7be6bc7bd6a6e1fa77808a96361c88/SBTi/temperature_score.py#L349)

**Problem:**
```
        if row[self.c.COLS.GHG_SCOPE12] is None or row[self.c.COLS.GHG_SCOPE3] is None:
            return (
                TemperatureScoreConfig.FALLBACK_SCORE,
                TemperatureScoreConfig.FALLBACK_SCORE,
            )
```

**Solution proposed:**

```
        if s3.isna()[self.c.COLS.GHG_SCOPE3] | s1s2.isna()[self.c.COLS.GHG_SCOPE12]:
            return (
                TemperatureScoreConfig.FALLBACK_SCORE,
                TemperatureScoreConfig.FALLBACK_SCORE,
            )
```

**Comment by max-tikehaucapital** [comment]
True. I will create a pull request for this bug.

**Comment by mountainrambler** [comment]
The issue with None vs .isna() has been resolved.
