### ISSUE TITLE
'pip install sbti' in README installs an old version

### ISSUE THREAD

**Issue by ogibbo** [ScienceBasedTargets/SBTi-finance-tool#300]
'pip install sbti' seems to install an old version from 2020: https://pypi.org/project/SBTi/

I think it should be changed to 'pip install sbti-finance-tool': https://pypi.org/project/sbti-finance-tool/

**Comment by mountainrambler** [comment]
Thank you for pointing out this error in the README file. Will fix in coming release. 
Note that all of the example notebooks use pip install sbti-finance-tool.
